/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as HackathonsRouteImport } from './routes/hackathons'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as HackathonsSlugRouteImport } from './routes/hackathons.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJudgeRouteImport } from './routes/_authenticated/judge'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as HackathonsSlugLeaderboardRouteImport } from './routes/hackathons.$slug.leaderboard'
import { Route as AuthenticatedTeamsNewRouteImport } from './routes/_authenticated/teams.new'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedOrganizerHackathonsRouteImport } from './routes/_authenticated/organizer.hackathons'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTeamsRouteImport } from './routes/_authenticated/admin.teams'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin.system'
import { Route as AuthenticatedAdminStorageRouteImport } from './routes/_authenticated/admin.storage'
import { Route as AuthenticatedAdminSponsorsRouteImport } from './routes/_authenticated/admin.sponsors'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin.resources'
import { Route as AuthenticatedAdminPlatformSettingsRouteImport } from './routes/_authenticated/admin.platform-settings'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMentorsRouteImport } from './routes/_authenticated/admin.mentors'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminJudgesRouteImport } from './routes/_authenticated/admin.judges'
import { Route as AuthenticatedAdminHackathonsRouteImport } from './routes/_authenticated/admin.hackathons'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminCommunityRouteImport } from './routes/_authenticated/admin.community'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAdminNotificationsRouteImport } from './routes/_authenticated/admin.admin-notifications'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminResourceRouteImport } from './routes/_authenticated/admin.$resource'
import { Route as ApiPublicVerifyCodeRouteImport } from './routes/api/public/verify.$code'
import { Route as ApiPublicCmsMediaSplatRouteImport } from './routes/api/public/cms-media.$'
import { Route as ApiPublicCertificatesCodeRouteImport } from './routes/api/public/certificates.$code'
import { Route as AuthenticatedTeamsTeamIdSubmissionRouteImport } from './routes/_authenticated/teams.$teamId.submission'
import { Route as AuthenticatedOrganizerHackathonsNewRouteImport } from './routes/_authenticated/organizer.hackathons.new'
import { Route as AuthenticatedOrganizerHackathonsHackathonIdRouteImport } from './routes/_authenticated/organizer.hackathons.$hackathonId'
import { Route as AuthenticatedJudgeSubmissionsSubmissionIdRouteImport } from './routes/_authenticated/judge.submissions.$submissionId'
import { Route as AuthenticatedJudgeHackathonsHackathonIdRouteImport } from './routes/_authenticated/judge.hackathons.$hackathonId'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'
import { Route as AuthenticatedAdminResourceNewRouteImport } from './routes/_authenticated/admin.$resource.new'
import { Route as AuthenticatedAdminResourceItemIdRouteImport } from './routes/_authenticated/admin.$resource.$itemId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsRoute = HackathonsRouteImport.update({
  id: '/hackathons',
  path: '/hackathons',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const HackathonsSlugRoute = HackathonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HackathonsRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJudgeRoute = AuthenticatedJudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const HackathonsSlugLeaderboardRoute =
  HackathonsSlugLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => HackathonsSlugRoute,
  } as any)
const AuthenticatedTeamsNewRoute = AuthenticatedTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTeamsRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)
const AuthenticatedOrganizerHackathonsRoute =
  AuthenticatedOrganizerHackathonsRouteImport.update({
    id: '/organizer/hackathons',
    path: '/organizer/hackathons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeamsRoute = AuthenticatedAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStorageRoute =
  AuthenticatedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSponsorsRoute =
  AuthenticatedAdminSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformSettingsRoute =
  AuthenticatedAdminPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMentorsRoute =
  AuthenticatedAdminMentorsRouteImport.update({
    id: '/mentors',
    path: '/mentors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminJudgesRoute =
  AuthenticatedAdminJudgesRouteImport.update({
    id: '/judges',
    path: '/judges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHackathonsRoute =
  AuthenticatedAdminHackathonsRouteImport.update({
    id: '/hackathons',
    path: '/hackathons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommunityRoute =
  AuthenticatedAdminCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminNotificationsRoute =
  AuthenticatedAdminAdminNotificationsRouteImport.update({
    id: '/admin-notifications',
    path: '/admin-notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourceRoute =
  AuthenticatedAdminResourceRouteImport.update({
    id: '/$resource',
    path: '/$resource',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicVerifyCodeRoute = ApiPublicVerifyCodeRouteImport.update({
  id: '/api/public/verify/$code',
  path: '/api/public/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmsMediaSplatRoute = ApiPublicCmsMediaSplatRouteImport.update({
  id: '/api/public/cms-media/$',
  path: '/api/public/cms-media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCertificatesCodeRoute =
  ApiPublicCertificatesCodeRouteImport.update({
    id: '/api/public/certificates/$code',
    path: '/api/public/certificates/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeamsTeamIdSubmissionRoute =
  AuthenticatedTeamsTeamIdSubmissionRouteImport.update({
    id: '/submission',
    path: '/submission',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const AuthenticatedOrganizerHackathonsNewRoute =
  AuthenticatedOrganizerHackathonsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrganizerHackathonsRoute,
  } as any)
const AuthenticatedOrganizerHackathonsHackathonIdRoute =
  AuthenticatedOrganizerHackathonsHackathonIdRouteImport.update({
    id: '/$hackathonId',
    path: '/$hackathonId',
    getParentRoute: () => AuthenticatedOrganizerHackathonsRoute,
  } as any)
const AuthenticatedJudgeSubmissionsSubmissionIdRoute =
  AuthenticatedJudgeSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AuthenticatedJudgeRoute,
  } as any)
const AuthenticatedJudgeHackathonsHackathonIdRoute =
  AuthenticatedJudgeHackathonsHackathonIdRouteImport.update({
    id: '/hackathons/$hackathonId',
    path: '/hackathons/$hackathonId',
    getParentRoute: () => AuthenticatedJudgeRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)
const AuthenticatedAdminResourceNewRoute =
  AuthenticatedAdminResourceNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminResourceRoute,
  } as any)
const AuthenticatedAdminResourceItemIdRoute =
  AuthenticatedAdminResourceItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedAdminResourceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/hackathons': typeof HackathonsRouteWithChildren
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/judge': typeof AuthenticatedJudgeRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRouteWithChildren
  '/resources/$slug': typeof ResourcesSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/$resource': typeof AuthenticatedAdminResourceRouteWithChildren
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/admin-notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/hackathons': typeof AuthenticatedAdminHackathonsRoute
  '/admin/judges': typeof AuthenticatedAdminJudgesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/mentors': typeof AuthenticatedAdminMentorsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/organizer/hackathons': typeof AuthenticatedOrganizerHackathonsRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/hackathons/$slug/leaderboard': typeof HackathonsSlugLeaderboardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$resource/$itemId': typeof AuthenticatedAdminResourceItemIdRoute
  '/admin/$resource/new': typeof AuthenticatedAdminResourceNewRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/judge/hackathons/$hackathonId': typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  '/judge/submissions/$submissionId': typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
  '/organizer/hackathons/$hackathonId': typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  '/organizer/hackathons/new': typeof AuthenticatedOrganizerHackathonsNewRoute
  '/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/api/public/certificates/$code': typeof ApiPublicCertificatesCodeRoute
  '/api/public/cms-media/$': typeof ApiPublicCmsMediaSplatRoute
  '/api/public/verify/$code': typeof ApiPublicVerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/hackathons': typeof HackathonsRouteWithChildren
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/judge': typeof AuthenticatedJudgeRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRouteWithChildren
  '/resources/$slug': typeof ResourcesSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/$resource': typeof AuthenticatedAdminResourceRouteWithChildren
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/admin-notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/hackathons': typeof AuthenticatedAdminHackathonsRoute
  '/admin/judges': typeof AuthenticatedAdminJudgesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/mentors': typeof AuthenticatedAdminMentorsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/organizer/hackathons': typeof AuthenticatedOrganizerHackathonsRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/hackathons/$slug/leaderboard': typeof HackathonsSlugLeaderboardRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$resource/$itemId': typeof AuthenticatedAdminResourceItemIdRoute
  '/admin/$resource/new': typeof AuthenticatedAdminResourceNewRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/judge/hackathons/$hackathonId': typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  '/judge/submissions/$submissionId': typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
  '/organizer/hackathons/$hackathonId': typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  '/organizer/hackathons/new': typeof AuthenticatedOrganizerHackathonsNewRoute
  '/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/api/public/certificates/$code': typeof ApiPublicCertificatesCodeRoute
  '/api/public/cms-media/$': typeof ApiPublicCmsMediaSplatRoute
  '/api/public/verify/$code': typeof ApiPublicVerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/hackathons': typeof HackathonsRouteWithChildren
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/judge': typeof AuthenticatedJudgeRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRouteWithChildren
  '/resources/$slug': typeof ResourcesSlugRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/_authenticated/admin/$resource': typeof AuthenticatedAdminResourceRouteWithChildren
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/admin-notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/hackathons': typeof AuthenticatedAdminHackathonsRoute
  '/_authenticated/admin/judges': typeof AuthenticatedAdminJudgesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/mentors': typeof AuthenticatedAdminMentorsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/_authenticated/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/admin/teams': typeof AuthenticatedAdminTeamsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/organizer/hackathons': typeof AuthenticatedOrganizerHackathonsRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/_authenticated/teams/new': typeof AuthenticatedTeamsNewRoute
  '/hackathons/$slug/leaderboard': typeof HackathonsSlugLeaderboardRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$resource/$itemId': typeof AuthenticatedAdminResourceItemIdRoute
  '/_authenticated/admin/$resource/new': typeof AuthenticatedAdminResourceNewRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/judge/hackathons/$hackathonId': typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  '/_authenticated/judge/submissions/$submissionId': typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
  '/_authenticated/organizer/hackathons/$hackathonId': typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  '/_authenticated/organizer/hackathons/new': typeof AuthenticatedOrganizerHackathonsNewRoute
  '/_authenticated/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/api/public/certificates/$code': typeof ApiPublicCertificatesCodeRoute
  '/api/public/cms-media/$': typeof ApiPublicCmsMediaSplatRoute
  '/api/public/verify/$code': typeof ApiPublicVerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/code-of-conduct'
    | '/community'
    | '/contact'
    | '/events'
    | '/faqs'
    | '/hackathons'
    | '/judges'
    | '/mentors'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/sponsors'
    | '/terms'
    | '/admin'
    | '/certificates'
    | '/dashboard'
    | '/invitations'
    | '/judge'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/teams'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/events/$slug'
    | '/hackathons/$slug'
    | '/resources/$slug'
    | '/verify/$code'
    | '/admin/$resource'
    | '/admin/activity'
    | '/admin/admin-notifications'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/audit-logs'
    | '/admin/community'
    | '/admin/content'
    | '/admin/email'
    | '/admin/emails'
    | '/admin/events'
    | '/admin/hackathons'
    | '/admin/judges'
    | '/admin/media'
    | '/admin/mentors'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/platform-settings'
    | '/admin/resources'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/storage'
    | '/admin/system'
    | '/admin/teams'
    | '/admin/users'
    | '/organizer/hackathons'
    | '/teams/$teamId'
    | '/teams/new'
    | '/hackathons/$slug/leaderboard'
    | '/admin/'
    | '/admin/$resource/$itemId'
    | '/admin/$resource/new'
    | '/admin/users/$userId'
    | '/judge/hackathons/$hackathonId'
    | '/judge/submissions/$submissionId'
    | '/organizer/hackathons/$hackathonId'
    | '/organizer/hackathons/new'
    | '/teams/$teamId/submission'
    | '/api/public/certificates/$code'
    | '/api/public/cms-media/$'
    | '/api/public/verify/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/code-of-conduct'
    | '/community'
    | '/contact'
    | '/events'
    | '/faqs'
    | '/hackathons'
    | '/judges'
    | '/mentors'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/sponsors'
    | '/terms'
    | '/certificates'
    | '/dashboard'
    | '/invitations'
    | '/judge'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/teams'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/events/$slug'
    | '/hackathons/$slug'
    | '/resources/$slug'
    | '/verify/$code'
    | '/admin/$resource'
    | '/admin/activity'
    | '/admin/admin-notifications'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/audit-logs'
    | '/admin/community'
    | '/admin/content'
    | '/admin/email'
    | '/admin/emails'
    | '/admin/events'
    | '/admin/hackathons'
    | '/admin/judges'
    | '/admin/media'
    | '/admin/mentors'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/platform-settings'
    | '/admin/resources'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/storage'
    | '/admin/system'
    | '/admin/teams'
    | '/admin/users'
    | '/organizer/hackathons'
    | '/teams/$teamId'
    | '/teams/new'
    | '/hackathons/$slug/leaderboard'
    | '/admin'
    | '/admin/$resource/$itemId'
    | '/admin/$resource/new'
    | '/admin/users/$userId'
    | '/judge/hackathons/$hackathonId'
    | '/judge/submissions/$submissionId'
    | '/organizer/hackathons/$hackathonId'
    | '/organizer/hackathons/new'
    | '/teams/$teamId/submission'
    | '/api/public/certificates/$code'
    | '/api/public/cms-media/$'
    | '/api/public/verify/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/code-of-conduct'
    | '/community'
    | '/contact'
    | '/events'
    | '/faqs'
    | '/hackathons'
    | '/judges'
    | '/mentors'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/sponsors'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/invitations'
    | '/_authenticated/judge'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/teams'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/onboarding'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/events/$slug'
    | '/hackathons/$slug'
    | '/resources/$slug'
    | '/verify/$code'
    | '/_authenticated/admin/$resource'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/admin-notifications'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/community'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/hackathons'
    | '/_authenticated/admin/judges'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/mentors'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/platform-settings'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sponsors'
    | '/_authenticated/admin/storage'
    | '/_authenticated/admin/system'
    | '/_authenticated/admin/teams'
    | '/_authenticated/admin/users'
    | '/_authenticated/organizer/hackathons'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/teams/new'
    | '/hackathons/$slug/leaderboard'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$resource/$itemId'
    | '/_authenticated/admin/$resource/new'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/judge/hackathons/$hackathonId'
    | '/_authenticated/judge/submissions/$submissionId'
    | '/_authenticated/organizer/hackathons/$hackathonId'
    | '/_authenticated/organizer/hackathons/new'
    | '/_authenticated/teams/$teamId/submission'
    | '/api/public/certificates/$code'
    | '/api/public/cms-media/$'
    | '/api/public/verify/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  HackathonsRoute: typeof HackathonsRouteWithChildren
  JudgesRoute: typeof JudgesRoute
  MentorsRoute: typeof MentorsRoute
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SponsorsRoute: typeof SponsorsRoute
  TermsRoute: typeof TermsRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiPublicCertificatesCodeRoute: typeof ApiPublicCertificatesCodeRoute
  ApiPublicCmsMediaSplatRoute: typeof ApiPublicCmsMediaSplatRoute
  ApiPublicVerifyCodeRoute: typeof ApiPublicVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons': {
      id: '/hackathons'
      path: '/hackathons'
      fullPath: '/hackathons'
      preLoaderRoute: typeof HackathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/hackathons/$slug': {
      id: '/hackathons/$slug'
      path: '/$slug'
      fullPath: '/hackathons/$slug'
      preLoaderRoute: typeof HackathonsSlugRouteImport
      parentRoute: typeof HackathonsRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judge': {
      id: '/_authenticated/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof AuthenticatedJudgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/hackathons/$slug/leaderboard': {
      id: '/hackathons/$slug/leaderboard'
      path: '/leaderboard'
      fullPath: '/hackathons/$slug/leaderboard'
      preLoaderRoute: typeof HackathonsSlugLeaderboardRouteImport
      parentRoute: typeof HackathonsSlugRoute
    }
    '/_authenticated/teams/new': {
      id: '/_authenticated/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AuthenticatedTeamsNewRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/organizer/hackathons': {
      id: '/_authenticated/organizer/hackathons'
      path: '/organizer/hackathons'
      fullPath: '/organizer/hackathons'
      preLoaderRoute: typeof AuthenticatedOrganizerHackathonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teams': {
      id: '/_authenticated/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AuthenticatedAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/storage': {
      id: '/_authenticated/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AuthenticatedAdminStorageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sponsors': {
      id: '/_authenticated/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AuthenticatedAdminSponsorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/platform-settings': {
      id: '/_authenticated/admin/platform-settings'
      path: '/platform-settings'
      fullPath: '/admin/platform-settings'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mentors': {
      id: '/_authenticated/admin/mentors'
      path: '/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AuthenticatedAdminMentorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/judges': {
      id: '/_authenticated/admin/judges'
      path: '/judges'
      fullPath: '/admin/judges'
      preLoaderRoute: typeof AuthenticatedAdminJudgesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hackathons': {
      id: '/_authenticated/admin/hackathons'
      path: '/hackathons'
      fullPath: '/admin/hackathons'
      preLoaderRoute: typeof AuthenticatedAdminHackathonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/community': {
      id: '/_authenticated/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthenticatedAdminCommunityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admin-notifications': {
      id: '/_authenticated/admin/admin-notifications'
      path: '/admin-notifications'
      fullPath: '/admin/admin-notifications'
      preLoaderRoute: typeof AuthenticatedAdminAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$resource': {
      id: '/_authenticated/admin/$resource'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AuthenticatedAdminResourceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/verify/$code': {
      id: '/api/public/verify/$code'
      path: '/api/public/verify/$code'
      fullPath: '/api/public/verify/$code'
      preLoaderRoute: typeof ApiPublicVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cms-media/$': {
      id: '/api/public/cms-media/$'
      path: '/api/public/cms-media/$'
      fullPath: '/api/public/cms-media/$'
      preLoaderRoute: typeof ApiPublicCmsMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/certificates/$code': {
      id: '/api/public/certificates/$code'
      path: '/api/public/certificates/$code'
      fullPath: '/api/public/certificates/$code'
      preLoaderRoute: typeof ApiPublicCertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/$teamId/submission': {
      id: '/_authenticated/teams/$teamId/submission'
      path: '/submission'
      fullPath: '/teams/$teamId/submission'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdSubmissionRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_authenticated/organizer/hackathons/new': {
      id: '/_authenticated/organizer/hackathons/new'
      path: '/new'
      fullPath: '/organizer/hackathons/new'
      preLoaderRoute: typeof AuthenticatedOrganizerHackathonsNewRouteImport
      parentRoute: typeof AuthenticatedOrganizerHackathonsRoute
    }
    '/_authenticated/organizer/hackathons/$hackathonId': {
      id: '/_authenticated/organizer/hackathons/$hackathonId'
      path: '/$hackathonId'
      fullPath: '/organizer/hackathons/$hackathonId'
      preLoaderRoute: typeof AuthenticatedOrganizerHackathonsHackathonIdRouteImport
      parentRoute: typeof AuthenticatedOrganizerHackathonsRoute
    }
    '/_authenticated/judge/submissions/$submissionId': {
      id: '/_authenticated/judge/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/judge/submissions/$submissionId'
      preLoaderRoute: typeof AuthenticatedJudgeSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedJudgeRoute
    }
    '/_authenticated/judge/hackathons/$hackathonId': {
      id: '/_authenticated/judge/hackathons/$hackathonId'
      path: '/hackathons/$hackathonId'
      fullPath: '/judge/hackathons/$hackathonId'
      preLoaderRoute: typeof AuthenticatedJudgeHackathonsHackathonIdRouteImport
      parentRoute: typeof AuthenticatedJudgeRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
    '/_authenticated/admin/$resource/new': {
      id: '/_authenticated/admin/$resource/new'
      path: '/new'
      fullPath: '/admin/$resource/new'
      preLoaderRoute: typeof AuthenticatedAdminResourceNewRouteImport
      parentRoute: typeof AuthenticatedAdminResourceRoute
    }
    '/_authenticated/admin/$resource/$itemId': {
      id: '/_authenticated/admin/$resource/$itemId'
      path: '/$itemId'
      fullPath: '/admin/$resource/$itemId'
      preLoaderRoute: typeof AuthenticatedAdminResourceItemIdRouteImport
      parentRoute: typeof AuthenticatedAdminResourceRoute
    }
  }
}

interface AuthenticatedAdminResourceRouteChildren {
  AuthenticatedAdminResourceItemIdRoute: typeof AuthenticatedAdminResourceItemIdRoute
  AuthenticatedAdminResourceNewRoute: typeof AuthenticatedAdminResourceNewRoute
}

const AuthenticatedAdminResourceRouteChildren: AuthenticatedAdminResourceRouteChildren =
  {
    AuthenticatedAdminResourceItemIdRoute:
      AuthenticatedAdminResourceItemIdRoute,
    AuthenticatedAdminResourceNewRoute: AuthenticatedAdminResourceNewRoute,
  }

const AuthenticatedAdminResourceRouteWithChildren =
  AuthenticatedAdminResourceRoute._addFileChildren(
    AuthenticatedAdminResourceRouteChildren,
  )

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminResourceRoute: typeof AuthenticatedAdminResourceRouteWithChildren
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAdminNotificationsRoute: typeof AuthenticatedAdminAdminNotificationsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminCommunityRoute: typeof AuthenticatedAdminCommunityRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminHackathonsRoute: typeof AuthenticatedAdminHackathonsRoute
  AuthenticatedAdminJudgesRoute: typeof AuthenticatedAdminJudgesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMentorsRoute: typeof AuthenticatedAdminMentorsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPlatformSettingsRoute: typeof AuthenticatedAdminPlatformSettingsRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSponsorsRoute: typeof AuthenticatedAdminSponsorsRoute
  AuthenticatedAdminStorageRoute: typeof AuthenticatedAdminStorageRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminTeamsRoute: typeof AuthenticatedAdminTeamsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminResourceRoute: AuthenticatedAdminResourceRouteWithChildren,
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminAdminNotificationsRoute:
    AuthenticatedAdminAdminNotificationsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminCommunityRoute: AuthenticatedAdminCommunityRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminHackathonsRoute: AuthenticatedAdminHackathonsRoute,
  AuthenticatedAdminJudgesRoute: AuthenticatedAdminJudgesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMentorsRoute: AuthenticatedAdminMentorsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminPlatformSettingsRoute:
    AuthenticatedAdminPlatformSettingsRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSponsorsRoute: AuthenticatedAdminSponsorsRoute,
  AuthenticatedAdminStorageRoute: AuthenticatedAdminStorageRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminTeamsRoute: AuthenticatedAdminTeamsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedJudgeRouteChildren {
  AuthenticatedJudgeHackathonsHackathonIdRoute: typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  AuthenticatedJudgeSubmissionsSubmissionIdRoute: typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
}

const AuthenticatedJudgeRouteChildren: AuthenticatedJudgeRouteChildren = {
  AuthenticatedJudgeHackathonsHackathonIdRoute:
    AuthenticatedJudgeHackathonsHackathonIdRoute,
  AuthenticatedJudgeSubmissionsSubmissionIdRoute:
    AuthenticatedJudgeSubmissionsSubmissionIdRoute,
}

const AuthenticatedJudgeRouteWithChildren =
  AuthenticatedJudgeRoute._addFileChildren(AuthenticatedJudgeRouteChildren)

interface AuthenticatedTeamsTeamIdRouteChildren {
  AuthenticatedTeamsTeamIdSubmissionRoute: typeof AuthenticatedTeamsTeamIdSubmissionRoute
}

const AuthenticatedTeamsTeamIdRouteChildren: AuthenticatedTeamsTeamIdRouteChildren =
  {
    AuthenticatedTeamsTeamIdSubmissionRoute:
      AuthenticatedTeamsTeamIdSubmissionRoute,
  }

const AuthenticatedTeamsTeamIdRouteWithChildren =
  AuthenticatedTeamsTeamIdRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteChildren,
  )

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRouteWithChildren
  AuthenticatedTeamsNewRoute: typeof AuthenticatedTeamsNewRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRouteWithChildren,
  AuthenticatedTeamsNewRoute: AuthenticatedTeamsNewRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedOrganizerHackathonsRouteChildren {
  AuthenticatedOrganizerHackathonsHackathonIdRoute: typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  AuthenticatedOrganizerHackathonsNewRoute: typeof AuthenticatedOrganizerHackathonsNewRoute
}

const AuthenticatedOrganizerHackathonsRouteChildren: AuthenticatedOrganizerHackathonsRouteChildren =
  {
    AuthenticatedOrganizerHackathonsHackathonIdRoute:
      AuthenticatedOrganizerHackathonsHackathonIdRoute,
    AuthenticatedOrganizerHackathonsNewRoute:
      AuthenticatedOrganizerHackathonsNewRoute,
  }

const AuthenticatedOrganizerHackathonsRouteWithChildren =
  AuthenticatedOrganizerHackathonsRoute._addFileChildren(
    AuthenticatedOrganizerHackathonsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedJudgeRoute: typeof AuthenticatedJudgeRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
  AuthenticatedOrganizerHackathonsRoute: typeof AuthenticatedOrganizerHackathonsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedJudgeRoute: AuthenticatedJudgeRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
  AuthenticatedOrganizerHackathonsRoute:
    AuthenticatedOrganizerHackathonsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface HackathonsSlugRouteChildren {
  HackathonsSlugLeaderboardRoute: typeof HackathonsSlugLeaderboardRoute
}

const HackathonsSlugRouteChildren: HackathonsSlugRouteChildren = {
  HackathonsSlugLeaderboardRoute: HackathonsSlugLeaderboardRoute,
}

const HackathonsSlugRouteWithChildren = HackathonsSlugRoute._addFileChildren(
  HackathonsSlugRouteChildren,
)

interface HackathonsRouteChildren {
  HackathonsSlugRoute: typeof HackathonsSlugRouteWithChildren
}

const HackathonsRouteChildren: HackathonsRouteChildren = {
  HackathonsSlugRoute: HackathonsSlugRouteWithChildren,
}

const HackathonsRouteWithChildren = HackathonsRoute._addFileChildren(
  HackathonsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  FaqsRoute: FaqsRoute,
  HackathonsRoute: HackathonsRouteWithChildren,
  JudgesRoute: JudgesRoute,
  MentorsRoute: MentorsRoute,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SponsorsRoute: SponsorsRoute,
  TermsRoute: TermsRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiPublicCertificatesCodeRoute: ApiPublicCertificatesCodeRoute,
  ApiPublicCmsMediaSplatRoute: ApiPublicCmsMediaSplatRoute,
  ApiPublicVerifyCodeRoute: ApiPublicVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
