/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as HackathonsRouteImport } from './routes/hackathons'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as HackathonsSlugRouteImport } from './routes/hackathons.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedJudgeRouteImport } from './routes/_authenticated/judge'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as HackathonsSlugLeaderboardRouteImport } from './routes/hackathons.$slug.leaderboard'
import { Route as AuthenticatedTeamsNewRouteImport } from './routes/_authenticated/teams.new'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams.$teamId'
import { Route as AuthenticatedOrganizerHackathonsRouteImport } from './routes/_authenticated/organizer.hackathons'
import { Route as AuthenticatedAdminPlatformSettingsRouteImport } from './routes/_authenticated/admin.platform-settings'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAdminNotificationsRouteImport } from './routes/_authenticated/admin.admin-notifications'
import { Route as AuthenticatedAdminResourceRouteImport } from './routes/_authenticated/admin.$resource'
import { Route as ApiPublicCmsMediaSplatRouteImport } from './routes/api/public/cms-media.$'
import { Route as ApiPublicCertificatesCodeRouteImport } from './routes/api/public/certificates.$code'
import { Route as AuthenticatedTeamsTeamIdSubmissionRouteImport } from './routes/_authenticated/teams.$teamId.submission'
import { Route as AuthenticatedOrganizerHackathonsNewRouteImport } from './routes/_authenticated/organizer.hackathons.new'
import { Route as AuthenticatedOrganizerHackathonsHackathonIdRouteImport } from './routes/_authenticated/organizer.hackathons.$hackathonId'
import { Route as AuthenticatedJudgeSubmissionsSubmissionIdRouteImport } from './routes/_authenticated/judge.submissions.$submissionId'
import { Route as AuthenticatedJudgeHackathonsHackathonIdRouteImport } from './routes/_authenticated/judge.hackathons.$hackathonId'
import { Route as AuthenticatedAdminResourceNewRouteImport } from './routes/_authenticated/admin.$resource.new'
import { Route as AuthenticatedAdminResourceItemIdRouteImport } from './routes/_authenticated/admin.$resource.$itemId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsRoute = HackathonsRouteImport.update({
  id: '/hackathons',
  path: '/hackathons',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsSlugRoute = HackathonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HackathonsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJudgeRoute = AuthenticatedJudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const HackathonsSlugLeaderboardRoute =
  HackathonsSlugLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => HackathonsSlugRoute,
  } as any)
const AuthenticatedTeamsNewRoute = AuthenticatedTeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTeamsRoute,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedTeamsRoute,
  } as any)
const AuthenticatedOrganizerHackathonsRoute =
  AuthenticatedOrganizerHackathonsRouteImport.update({
    id: '/organizer/hackathons',
    path: '/organizer/hackathons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlatformSettingsRoute =
  AuthenticatedAdminPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminNotificationsRoute =
  AuthenticatedAdminAdminNotificationsRouteImport.update({
    id: '/admin-notifications',
    path: '/admin-notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResourceRoute =
  AuthenticatedAdminResourceRouteImport.update({
    id: '/$resource',
    path: '/$resource',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCmsMediaSplatRoute = ApiPublicCmsMediaSplatRouteImport.update({
  id: '/api/public/cms-media/$',
  path: '/api/public/cms-media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCertificatesCodeRoute =
  ApiPublicCertificatesCodeRouteImport.update({
    id: '/api/public/certificates/$code',
    path: '/api/public/certificates/$code',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeamsTeamIdSubmissionRoute =
  AuthenticatedTeamsTeamIdSubmissionRouteImport.update({
    id: '/submission',
    path: '/submission',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)
const AuthenticatedOrganizerHackathonsNewRoute =
  AuthenticatedOrganizerHackathonsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrganizerHackathonsRoute,
  } as any)
const AuthenticatedOrganizerHackathonsHackathonIdRoute =
  AuthenticatedOrganizerHackathonsHackathonIdRouteImport.update({
    id: '/$hackathonId',
    path: '/$hackathonId',
    getParentRoute: () => AuthenticatedOrganizerHackathonsRoute,
  } as any)
const AuthenticatedJudgeSubmissionsSubmissionIdRoute =
  AuthenticatedJudgeSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AuthenticatedJudgeRoute,
  } as any)
const AuthenticatedJudgeHackathonsHackathonIdRoute =
  AuthenticatedJudgeHackathonsHackathonIdRouteImport.update({
    id: '/hackathons/$hackathonId',
    path: '/hackathons/$hackathonId',
    getParentRoute: () => AuthenticatedJudgeRoute,
  } as any)
const AuthenticatedAdminResourceNewRoute =
  AuthenticatedAdminResourceNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminResourceRoute,
  } as any)
const AuthenticatedAdminResourceItemIdRoute =
  AuthenticatedAdminResourceItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedAdminResourceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/hackathons': typeof HackathonsRouteWithChildren
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/judge': typeof AuthenticatedJudgeRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/$resource': typeof AuthenticatedAdminResourceRouteWithChildren
  '/admin/admin-notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/organizer/hackathons': typeof AuthenticatedOrganizerHackathonsRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/hackathons/$slug/leaderboard': typeof HackathonsSlugLeaderboardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$resource/$itemId': typeof AuthenticatedAdminResourceItemIdRoute
  '/admin/$resource/new': typeof AuthenticatedAdminResourceNewRoute
  '/judge/hackathons/$hackathonId': typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  '/judge/submissions/$submissionId': typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
  '/organizer/hackathons/$hackathonId': typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  '/organizer/hackathons/new': typeof AuthenticatedOrganizerHackathonsNewRoute
  '/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/api/public/certificates/$code': typeof ApiPublicCertificatesCodeRoute
  '/api/public/cms-media/$': typeof ApiPublicCmsMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/hackathons': typeof HackathonsRouteWithChildren
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/judge': typeof AuthenticatedJudgeRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/$resource': typeof AuthenticatedAdminResourceRouteWithChildren
  '/admin/admin-notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/organizer/hackathons': typeof AuthenticatedOrganizerHackathonsRouteWithChildren
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/teams/new': typeof AuthenticatedTeamsNewRoute
  '/hackathons/$slug/leaderboard': typeof HackathonsSlugLeaderboardRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/$resource/$itemId': typeof AuthenticatedAdminResourceItemIdRoute
  '/admin/$resource/new': typeof AuthenticatedAdminResourceNewRoute
  '/judge/hackathons/$hackathonId': typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  '/judge/submissions/$submissionId': typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
  '/organizer/hackathons/$hackathonId': typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  '/organizer/hackathons/new': typeof AuthenticatedOrganizerHackathonsNewRoute
  '/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/api/public/certificates/$code': typeof ApiPublicCertificatesCodeRoute
  '/api/public/cms-media/$': typeof ApiPublicCmsMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/hackathons': typeof HackathonsRouteWithChildren
  '/judges': typeof JudgesRoute
  '/mentors': typeof MentorsRoute
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/judge': typeof AuthenticatedJudgeRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/hackathons/$slug': typeof HackathonsSlugRouteWithChildren
  '/verify/$code': typeof VerifyCodeRoute
  '/_authenticated/admin/$resource': typeof AuthenticatedAdminResourceRouteWithChildren
  '/_authenticated/admin/admin-notifications': typeof AuthenticatedAdminAdminNotificationsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/platform-settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/_authenticated/organizer/hackathons': typeof AuthenticatedOrganizerHackathonsRouteWithChildren
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/_authenticated/teams/new': typeof AuthenticatedTeamsNewRoute
  '/hackathons/$slug/leaderboard': typeof HackathonsSlugLeaderboardRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/$resource/$itemId': typeof AuthenticatedAdminResourceItemIdRoute
  '/_authenticated/admin/$resource/new': typeof AuthenticatedAdminResourceNewRoute
  '/_authenticated/judge/hackathons/$hackathonId': typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  '/_authenticated/judge/submissions/$submissionId': typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
  '/_authenticated/organizer/hackathons/$hackathonId': typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  '/_authenticated/organizer/hackathons/new': typeof AuthenticatedOrganizerHackathonsNewRoute
  '/_authenticated/teams/$teamId/submission': typeof AuthenticatedTeamsTeamIdSubmissionRoute
  '/api/public/certificates/$code': typeof ApiPublicCertificatesCodeRoute
  '/api/public/cms-media/$': typeof ApiPublicCmsMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/code-of-conduct'
    | '/community'
    | '/contact'
    | '/events'
    | '/faqs'
    | '/hackathons'
    | '/judges'
    | '/mentors'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/sponsors'
    | '/terms'
    | '/admin'
    | '/certificates'
    | '/dashboard'
    | '/invitations'
    | '/judge'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/teams'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/hackathons/$slug'
    | '/verify/$code'
    | '/admin/$resource'
    | '/admin/admin-notifications'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/email'
    | '/admin/platform-settings'
    | '/organizer/hackathons'
    | '/teams/$teamId'
    | '/teams/new'
    | '/hackathons/$slug/leaderboard'
    | '/admin/'
    | '/admin/$resource/$itemId'
    | '/admin/$resource/new'
    | '/judge/hackathons/$hackathonId'
    | '/judge/submissions/$submissionId'
    | '/organizer/hackathons/$hackathonId'
    | '/organizer/hackathons/new'
    | '/teams/$teamId/submission'
    | '/api/public/certificates/$code'
    | '/api/public/cms-media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/code-of-conduct'
    | '/community'
    | '/contact'
    | '/events'
    | '/faqs'
    | '/hackathons'
    | '/judges'
    | '/mentors'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/sponsors'
    | '/terms'
    | '/certificates'
    | '/dashboard'
    | '/invitations'
    | '/judge'
    | '/notifications'
    | '/profile'
    | '/settings'
    | '/teams'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/hackathons/$slug'
    | '/verify/$code'
    | '/admin/$resource'
    | '/admin/admin-notifications'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/email'
    | '/admin/platform-settings'
    | '/organizer/hackathons'
    | '/teams/$teamId'
    | '/teams/new'
    | '/hackathons/$slug/leaderboard'
    | '/admin'
    | '/admin/$resource/$itemId'
    | '/admin/$resource/new'
    | '/judge/hackathons/$hackathonId'
    | '/judge/submissions/$submissionId'
    | '/organizer/hackathons/$hackathonId'
    | '/organizer/hackathons/new'
    | '/teams/$teamId/submission'
    | '/api/public/certificates/$code'
    | '/api/public/cms-media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/code-of-conduct'
    | '/community'
    | '/contact'
    | '/events'
    | '/faqs'
    | '/hackathons'
    | '/judges'
    | '/mentors'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/resources'
    | '/sponsors'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/invitations'
    | '/_authenticated/judge'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/teams'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/blog/$slug'
    | '/hackathons/$slug'
    | '/verify/$code'
    | '/_authenticated/admin/$resource'
    | '/_authenticated/admin/admin-notifications'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/platform-settings'
    | '/_authenticated/organizer/hackathons'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/teams/new'
    | '/hackathons/$slug/leaderboard'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/$resource/$itemId'
    | '/_authenticated/admin/$resource/new'
    | '/_authenticated/judge/hackathons/$hackathonId'
    | '/_authenticated/judge/submissions/$submissionId'
    | '/_authenticated/organizer/hackathons/$hackathonId'
    | '/_authenticated/organizer/hackathons/new'
    | '/_authenticated/teams/$teamId/submission'
    | '/api/public/certificates/$code'
    | '/api/public/cms-media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqsRoute: typeof FaqsRoute
  HackathonsRoute: typeof HackathonsRouteWithChildren
  JudgesRoute: typeof JudgesRoute
  MentorsRoute: typeof MentorsRoute
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SponsorsRoute: typeof SponsorsRoute
  TermsRoute: typeof TermsRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiPublicCertificatesCodeRoute: typeof ApiPublicCertificatesCodeRoute
  ApiPublicCmsMediaSplatRoute: typeof ApiPublicCmsMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons': {
      id: '/hackathons'
      path: '/hackathons'
      fullPath: '/hackathons'
      preLoaderRoute: typeof HackathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$slug': {
      id: '/hackathons/$slug'
      path: '/$slug'
      fullPath: '/hackathons/$slug'
      preLoaderRoute: typeof HackathonsSlugRouteImport
      parentRoute: typeof HackathonsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/judge': {
      id: '/_authenticated/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof AuthenticatedJudgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/hackathons/$slug/leaderboard': {
      id: '/hackathons/$slug/leaderboard'
      path: '/leaderboard'
      fullPath: '/hackathons/$slug/leaderboard'
      preLoaderRoute: typeof HackathonsSlugLeaderboardRouteImport
      parentRoute: typeof HackathonsSlugRoute
    }
    '/_authenticated/teams/new': {
      id: '/_authenticated/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof AuthenticatedTeamsNewRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/organizer/hackathons': {
      id: '/_authenticated/organizer/hackathons'
      path: '/organizer/hackathons'
      fullPath: '/organizer/hackathons'
      preLoaderRoute: typeof AuthenticatedOrganizerHackathonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/platform-settings': {
      id: '/_authenticated/admin/platform-settings'
      path: '/platform-settings'
      fullPath: '/admin/platform-settings'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admin-notifications': {
      id: '/_authenticated/admin/admin-notifications'
      path: '/admin-notifications'
      fullPath: '/admin/admin-notifications'
      preLoaderRoute: typeof AuthenticatedAdminAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$resource': {
      id: '/_authenticated/admin/$resource'
      path: '/$resource'
      fullPath: '/admin/$resource'
      preLoaderRoute: typeof AuthenticatedAdminResourceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cms-media/$': {
      id: '/api/public/cms-media/$'
      path: '/api/public/cms-media/$'
      fullPath: '/api/public/cms-media/$'
      preLoaderRoute: typeof ApiPublicCmsMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/certificates/$code': {
      id: '/api/public/certificates/$code'
      path: '/api/public/certificates/$code'
      fullPath: '/api/public/certificates/$code'
      preLoaderRoute: typeof ApiPublicCertificatesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/$teamId/submission': {
      id: '/_authenticated/teams/$teamId/submission'
      path: '/submission'
      fullPath: '/teams/$teamId/submission'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdSubmissionRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
    '/_authenticated/organizer/hackathons/new': {
      id: '/_authenticated/organizer/hackathons/new'
      path: '/new'
      fullPath: '/organizer/hackathons/new'
      preLoaderRoute: typeof AuthenticatedOrganizerHackathonsNewRouteImport
      parentRoute: typeof AuthenticatedOrganizerHackathonsRoute
    }
    '/_authenticated/organizer/hackathons/$hackathonId': {
      id: '/_authenticated/organizer/hackathons/$hackathonId'
      path: '/$hackathonId'
      fullPath: '/organizer/hackathons/$hackathonId'
      preLoaderRoute: typeof AuthenticatedOrganizerHackathonsHackathonIdRouteImport
      parentRoute: typeof AuthenticatedOrganizerHackathonsRoute
    }
    '/_authenticated/judge/submissions/$submissionId': {
      id: '/_authenticated/judge/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/judge/submissions/$submissionId'
      preLoaderRoute: typeof AuthenticatedJudgeSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedJudgeRoute
    }
    '/_authenticated/judge/hackathons/$hackathonId': {
      id: '/_authenticated/judge/hackathons/$hackathonId'
      path: '/hackathons/$hackathonId'
      fullPath: '/judge/hackathons/$hackathonId'
      preLoaderRoute: typeof AuthenticatedJudgeHackathonsHackathonIdRouteImport
      parentRoute: typeof AuthenticatedJudgeRoute
    }
    '/_authenticated/admin/$resource/new': {
      id: '/_authenticated/admin/$resource/new'
      path: '/new'
      fullPath: '/admin/$resource/new'
      preLoaderRoute: typeof AuthenticatedAdminResourceNewRouteImport
      parentRoute: typeof AuthenticatedAdminResourceRoute
    }
    '/_authenticated/admin/$resource/$itemId': {
      id: '/_authenticated/admin/$resource/$itemId'
      path: '/$itemId'
      fullPath: '/admin/$resource/$itemId'
      preLoaderRoute: typeof AuthenticatedAdminResourceItemIdRouteImport
      parentRoute: typeof AuthenticatedAdminResourceRoute
    }
  }
}

interface AuthenticatedAdminResourceRouteChildren {
  AuthenticatedAdminResourceItemIdRoute: typeof AuthenticatedAdminResourceItemIdRoute
  AuthenticatedAdminResourceNewRoute: typeof AuthenticatedAdminResourceNewRoute
}

const AuthenticatedAdminResourceRouteChildren: AuthenticatedAdminResourceRouteChildren =
  {
    AuthenticatedAdminResourceItemIdRoute:
      AuthenticatedAdminResourceItemIdRoute,
    AuthenticatedAdminResourceNewRoute: AuthenticatedAdminResourceNewRoute,
  }

const AuthenticatedAdminResourceRouteWithChildren =
  AuthenticatedAdminResourceRoute._addFileChildren(
    AuthenticatedAdminResourceRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminResourceRoute: typeof AuthenticatedAdminResourceRouteWithChildren
  AuthenticatedAdminAdminNotificationsRoute: typeof AuthenticatedAdminAdminNotificationsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminPlatformSettingsRoute: typeof AuthenticatedAdminPlatformSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminResourceRoute: AuthenticatedAdminResourceRouteWithChildren,
  AuthenticatedAdminAdminNotificationsRoute:
    AuthenticatedAdminAdminNotificationsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
  AuthenticatedAdminPlatformSettingsRoute:
    AuthenticatedAdminPlatformSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedJudgeRouteChildren {
  AuthenticatedJudgeHackathonsHackathonIdRoute: typeof AuthenticatedJudgeHackathonsHackathonIdRoute
  AuthenticatedJudgeSubmissionsSubmissionIdRoute: typeof AuthenticatedJudgeSubmissionsSubmissionIdRoute
}

const AuthenticatedJudgeRouteChildren: AuthenticatedJudgeRouteChildren = {
  AuthenticatedJudgeHackathonsHackathonIdRoute:
    AuthenticatedJudgeHackathonsHackathonIdRoute,
  AuthenticatedJudgeSubmissionsSubmissionIdRoute:
    AuthenticatedJudgeSubmissionsSubmissionIdRoute,
}

const AuthenticatedJudgeRouteWithChildren =
  AuthenticatedJudgeRoute._addFileChildren(AuthenticatedJudgeRouteChildren)

interface AuthenticatedTeamsTeamIdRouteChildren {
  AuthenticatedTeamsTeamIdSubmissionRoute: typeof AuthenticatedTeamsTeamIdSubmissionRoute
}

const AuthenticatedTeamsTeamIdRouteChildren: AuthenticatedTeamsTeamIdRouteChildren =
  {
    AuthenticatedTeamsTeamIdSubmissionRoute:
      AuthenticatedTeamsTeamIdSubmissionRoute,
  }

const AuthenticatedTeamsTeamIdRouteWithChildren =
  AuthenticatedTeamsTeamIdRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteChildren,
  )

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRouteWithChildren
  AuthenticatedTeamsNewRoute: typeof AuthenticatedTeamsNewRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRouteWithChildren,
  AuthenticatedTeamsNewRoute: AuthenticatedTeamsNewRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedOrganizerHackathonsRouteChildren {
  AuthenticatedOrganizerHackathonsHackathonIdRoute: typeof AuthenticatedOrganizerHackathonsHackathonIdRoute
  AuthenticatedOrganizerHackathonsNewRoute: typeof AuthenticatedOrganizerHackathonsNewRoute
}

const AuthenticatedOrganizerHackathonsRouteChildren: AuthenticatedOrganizerHackathonsRouteChildren =
  {
    AuthenticatedOrganizerHackathonsHackathonIdRoute:
      AuthenticatedOrganizerHackathonsHackathonIdRoute,
    AuthenticatedOrganizerHackathonsNewRoute:
      AuthenticatedOrganizerHackathonsNewRoute,
  }

const AuthenticatedOrganizerHackathonsRouteWithChildren =
  AuthenticatedOrganizerHackathonsRoute._addFileChildren(
    AuthenticatedOrganizerHackathonsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedJudgeRoute: typeof AuthenticatedJudgeRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
  AuthenticatedOrganizerHackathonsRoute: typeof AuthenticatedOrganizerHackathonsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedJudgeRoute: AuthenticatedJudgeRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
  AuthenticatedOrganizerHackathonsRoute:
    AuthenticatedOrganizerHackathonsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface HackathonsSlugRouteChildren {
  HackathonsSlugLeaderboardRoute: typeof HackathonsSlugLeaderboardRoute
}

const HackathonsSlugRouteChildren: HackathonsSlugRouteChildren = {
  HackathonsSlugLeaderboardRoute: HackathonsSlugLeaderboardRoute,
}

const HackathonsSlugRouteWithChildren = HackathonsSlugRoute._addFileChildren(
  HackathonsSlugRouteChildren,
)

interface HackathonsRouteChildren {
  HackathonsSlugRoute: typeof HackathonsSlugRouteWithChildren
}

const HackathonsRouteChildren: HackathonsRouteChildren = {
  HackathonsSlugRoute: HackathonsSlugRouteWithChildren,
}

const HackathonsRouteWithChildren = HackathonsRoute._addFileChildren(
  HackathonsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqsRoute: FaqsRoute,
  HackathonsRoute: HackathonsRouteWithChildren,
  JudgesRoute: JudgesRoute,
  MentorsRoute: MentorsRoute,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SponsorsRoute: SponsorsRoute,
  TermsRoute: TermsRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiPublicCertificatesCodeRoute: ApiPublicCertificatesCodeRoute,
  ApiPublicCmsMediaSplatRoute: ApiPublicCmsMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
